# set base image (host OS)
FROM centos:7

RUN yum -y install epel-release && yum clean all
RUN yum -y install python3 python3-pip && yum clean all

# set the working directory in the container
WORKDIR /code

# copy the dependencies file to the working directory
COPY ./requirements.txt .

# install dependencies
RUN pip3 install -r requirements.txt

# copy the content of the local src directory to the working directory
COPY ./src/ .

# command to run on container start
CMD [ "python", "./server.py" ]