# set base image (host OS)
FROM ubuntu:18.04

RUN apt-get -y update
RUN apt-get -y install python3 python3-pip && apt-get clean

# set the working directory in the container
WORKDIR /code

# copy the dependencies file to the working directory
COPY ./requirements.txt .

# install dependencies
RUN pip3 install -r requirements.txt

# copy the content of the local src directory to the working directory
COPY ./src/ .

# command to run on container start
CMD [ "python", "./server.py" ]